apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: ha-mosquitto
  name: ha-mosquitto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
