apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: mosquitto
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mosquitto
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: mosquitto
    spec:
      initContainers:
        - name: init
          image: alpine:latest
          command: ["sh", "-c", "while [ ! -f /mosquitto/ready.txt ]; do sleep 1; done; echo ok"]
          volumeMounts:
             - name: ha-mosquitto               
               mountPath: /mosquitto
    
      containers:
        - image: eclipse-mosquitto
          name: mosquitto
          ports:
            - containerPort: 1883
              protocol: TCP
          volumeMounts:
            - mountPath: /mosquitto
              name: ha-mosquitto
      restartPolicy: Always
      volumes:
        - name: ha-mosquitto
          persistentVolumeClaim:
            claimName: ha-mosquitto
