apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: mosquitto
  name: mosquitto
spec:
  type: NodePort
  ports:
    - name: "1883"
      port: 1883
      targetPort: 1883
      nodePort: 31883
  selector:
    io.kompose.service: mosquitto
