apiVersion: apps/v1
kind: Deployment
metadata:
  name: ha-camera-mcp
  labels:
    app: ha-camera-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ha-camera-mcp
  template:
    metadata:
      labels:
        app: ha-camera-mcp
    spec:
      containers:
        - name: ha-camera-mcp
          image: ghcr.io/smarter-project/homeassistant-camera-mcp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              protocol: TCP
          env:
            - name: DANGEROUSLY_OMIT_AUTH
              value: "true"
          volumeMounts:
            - name: camera-images
              mountPath: /images
      imagePullSecrets:
        - name: arm-artifactory-secret
      volumes:
        - name: camera-images
          persistentVolumeClaim:
            claimName: camera-images
---
apiVersion: v1
kind: Service
metadata:
  name: ha-camera-mcp-service
  labels:
    app: ha-camera-mcp
spec:
  type: NodePort
  selector:
    app: ha-camera-mcp
  ports:
    - name: "9000"
      port: 9000          # Port the service is exposed on internally (ClusterIP)
      targetPort: 9000    # Port the container listens on
      nodePort:  30900    # Optional: the external port on each node
 
