- id: '1748955940402'
  alias: test1
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.motion
    to: 'on'
  conditions:
  - condition: state
    entity_id: alarm_control_panel.home_alarm_2
    state: armed_away
  actions:
  - action: persistent_notification.create
    metadata: {}
    data:
      message: Alarm Triggered
  - action: alarm_control_panel.alarm_trigger
    metadata: {}
    data: {}
    target:
      entity_id: alarm_control_panel.home_alarm_2
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - action: siren.turn_on
    metadata: {}
    data:
      duration: '10'
    target:
      entity_id: siren.siren_siren
  - delay:
      hours: 0
      minutes: 0
      seconds: 20
      milliseconds: 0
  - action: siren.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: siren.siren_siren
  mode: single
